/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 841fd8740ed6333de2ae2d0c633f4569)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	SITE_URL: string;
	AUTH_SECRET: string;
	EMAIL_API_KEY: string;
	EMAIL_FROM: string;
	EMAIL_API_URL: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "AUTH_SECRET" | "EMAIL_API_KEY" | "EMAIL_FROM" | "EMAIL_API_URL">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}